charity_box/organizations/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class OrganizationForm(FlaskForm):
    name = StringField('שם', validators=[DataRequired()])
    street = StringField('רחוב', validators=[DataRequired()])
    city = StringField('עיר', validators=[DataRequired()])
    country = StringField('מדינה', validators=[DataRequired()])
    submit = SubmitField('צור אירגון')

class OrganizationUpdateForm(FlaskForm):
    name = StringField('שם', validators=[DataRequired()])
    address = StringField('כתובת', validators=[DataRequired()])
    submit = SubmitField('עדכן אירגון')

charity_box/__init__.py
import os
from flask import Flask
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
from charity_box.organizations.views import organizations

app = Flask(__name__)

basedir = os.path.abspath(os.path.dirname(__file__))
cred_file = os.path.join(os.path.dirname(__file__), "serviceAccountKey.json")
cred = credentials.Certificate("charity_box/serviceAccountKey.json")
firebase_admin.initialize_app(cred)

db = firestore.client()

app.register_blueprint(organizations, url_prefix='/organizations')

charity_box/organizations/views.py
from flask import render_template, request, Blueprint, flash, redirect, url_for
from charity_box.organizations.forms import OrganizationForm, OrganizationUpdateForm
import charity_box
organizations = Blueprint('organizations', __name__)


@organizations.route('/')
def index():
    organization_list = charity_box.db.collection('organizations').get()
    amounts_list = {}
    for org in organization_list:
        total = 0
        boxes = org.to_dict()['boxes']
        for box in boxes:
            box_ref = charity_box.db.collection('boxes').document(box.id)
            amount = box_ref.get().to_dict()['amount']
            total = total + amount
        amounts_list[org.to_dict()['name']] = total
    return render_template('organizations/index.html', organizations=organization_list, amounts=amounts_list)


@organizations.route('/create', methods=['GET', 'POST'])
def create():
    form = OrganizationForm()

    if form.validate_on_submit():
        new_organization = form.name
        charity_box.db.collection('organizations').add(new_organization)
        flash("New Organization Created")
        return redirect(url_for('organizations.index'))

    return render_template('organizations/create.html', form=form)


@organizations.route('/<string:organization_id>/update', methods=['GET', 'POST'])
def update(organization_id):
    organization = charity_box.db.collection('organization').document(organization_id).get()
    form = OrganizationUpdateForm()
    if form.validate_on_submit():
        organization.name = form.name.data
        organization.address = form.address.data
        charity_box.db.collection('organization').document(organization_id).update(organization)
        flash('Organization Updated')
        return redirect(url_for('organizations.index'))
    # Pass back the old blog post information ,so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.name.data = organization.name
        form.address.data = organization.address
        
    return render_template('organizations/update.html', title='Update',
                           form=form)

charity_box/templates/organizations/index.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <table style="width:100%" >
      <th style="text-align:right"><h1>אירגונים</h1></th>
      <th style="text-align:left"><a href="{{ url_for('organizations.create') }}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">הוסף אירגון</a></th>
    </table>
    
    <table id=data class="table table-striped table-hover row-clickable">
        <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">שם</th>
              <th scope="col">כתובת</th>
              <th scope="col">הכנסות</th>
            </tr>
        </thead>
        <tbody>
            {% for organization in organizations %}
            <tr class='clickable-row' data-href="{{ url_for('organizations.update',organization_id=organization.id) }}" method = POST>
              <th scope="row">{{organization.id}}</th>
              <td>{{organization.to_dict().name}}</td>
              <td>{{organization.to_dict().address}}</td>
              <td>{{ amounts[organization.to_dict().name]}}</td>
            </tr>
            {% endfor %}   
        </tbody>
    </table>
</div>
{% endblock %}

{% block scripts %}
  <script>
    // add js for table to make it searchable and orderable
    $(document).ready(function () {
      $('#data').DataTable({
        columns: [
          {searchable: false},
          {orderable: true, searchable: true},
          {orderable: true, searchable: true},
          null],
      });
    });

    // make table rows clickable
   jQuery(document).ready(function($) { 
    $(".clickable-row").click(function() {
       // alert($(this).data("href"));
        window.location = $(this).data("href");
    });
});
  </script>
{% endblock %}